version: '3.1'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=openhubusr
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=openhubdb
    ports:
      - 5432:5432
    container_name: openhub-postgresql