sudo: false
language: node_js
node_js:
  - "8"

before_install:
  - nvm install 8
  - nvm use 8

env:
  - TRAVIS_NODE_VERSION="8"

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn deploy:dev
  - yarn deploy:prod

after_success:
  - npm run codecov
