export const devColor = 'rgba(0, 0, 255, 0.05)'
export const primaryColor = '#EDEDED'
export const secondaryColor = '#2A3F54'
export const lightColor = '#dfdfdf'
export const darkColor = '#000'
export const negativeColor = '#F04A44'
export const positiveColor = '#579a35'
export const warningColor = '#f38c0c'
